### ISSUE TITLE
Search Results scrollbar covered partially by Close button

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#142] opened 2015-11-18 03:00 UTC
On all browsers (Safari is less noticeable because of how scrollbars work but still has the issue) the vertical scrollbar in the search result panel partially covers the Close button.  There should not be an overlap.

**Comment by r12s** [comment] 2016-02-29 17:51
I cannot replicate this. @kilianc has this been fixed and the issue not closed?

**Comment by kilianc** [comment] 2016-02-29 18:00
I think I was able to replicate on IE and if you have scrollbars with background on

**Comment by spocke** [comment] 2016-03-09 15:41
Oops dupe of #309

**Comment by Afraithe** [comment] 2016-03-10 15:47
![3gvlwzm](https://cloud.githubusercontent.com/assets/130875/13674935/b9b0b56e-e6df-11e5-857c-a8b0e229a068.png)
Also the scroll is shown then no results are returned.

**Comment by r12s** [comment] 2017-04-25 04:22
Issue resolved with update to search / implementation of Algolia `docsearch`.

**Closed by r12s** 2017-04-25 04:22 UTC
Labels: bug
