### ISSUE TITLE
tiny para Balde de Laravel

### ISSUE THREAD

**Issue by yassercf** [tinymce/tinymce-docs#1710] opened 2020-10-13 18:54 UTC
Poseen alguna integracion de tiny para Laravel con Blade

**Comment by tylerkelly13** [comment] 2020-10-13 23:32
Sorry, we can only accept issues in English. Please reopen or open a new issue if you can translate your issue/question into English.
Note: I see the word Laravel, so this may also be a duplicate of #1627

**Closed by tylerkelly13** 2020-10-13 23:33 UTC

**Comment by yassercf** [comment] 2020-10-14 23:33
You have some tiny integration for Laravel with Blade
