### ISSUE TITLE
Search in API reference links to wrong URL

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#610] opened 2017-10-24 22:43 UTC
Search for "getContent"

A result is returned in the search, but the link is wrong.

It should go to https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#getcontent

Instead, it goes to https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#editor

This occurs for all pages in the API reference and makes it significantly more difficult to use.

**Comment by fyrkant** [comment] 2017-10-31 13:13
This was caused by a problem with the algolia docsearch config, I did a PR to the file that has now been merged in and it seems to be working better!

**Closed by fyrkant** 2017-10-31 13:13 UTC
Labels: bug
