### ISSUE TITLE
I have created a function to upload to firebase but how do I pass the 'image file' to my function? I have looked into images_upload handler but how do I access the user uploaded file inside that function?

### ISSUE THREAD

**Issue by yashboura303** [tinymce/tinymce-docs#1697] opened 2020-10-08 19:16 UTC
> *affected page: https://www.tiny.cloud/docs/integrations/react/*

**Comment by tylerkelly13** [comment] 2020-10-09 00:18
Marking this issue as a duplicate of #1698 and closing

**Closed by tylerkelly13** 2020-10-09 00:18 UTC
Labels: duplicate
