### ISSUE TITLE
content-filtering: Duplicate element IDs / Anchors not working

### ISSUE THREAD

**Issue by staabm** [tinymce/tinymce-docs#287] opened 2016-01-25 08:26 UTC
On https://www.tinymce.com/docs/configure/content-filtering/ most of the "Example" headlines link to a `#example` element which is not unique on the page

**Comment by r12s** [comment] 2016-02-24 17:15
Thanks @staabm this appears to be true for all h5 level header tags. The issue is noted and I'll look at a fix to the design.

**Comment by kilianc** [comment] 2016-03-05 22:54
@staabm thanks for contributing, good catch! @r12s I think is still useful to "anchor" to a particular example. We should find a way to have `https://www.tinymce.com/docs/configure/content-filtering/#allow_conditional_comments-example` or something.

I'll look into it.

**Comment by tylerkelly13** [comment] 2019-12-11 01:17
This issue has been fixed in the TinyMCE 5.1 documentation release.

**Closed by tylerkelly13** 2019-12-11 01:17 UTC
Labels: bug
