### ISSUE TITLE
Problem with page demo/file-picker.md

### ISSUE THREAD

**Issue by 256tjq1l9mbzvh17lmosharklaserscom** [tinymce/tinymce-docs#684] opened 2018-05-07 14:36 UTC
broken codepen. Chrome66 + uBlockOrigin. I will not reply to this bug.

> *affected page: https://www.tinymce.com/docs/demo/file-picker/*

Chrome's inspector log follows

GET https://www.googleadservices.com/pagead/conversion.js 0 ()
(index):7839 GET https://snap.licdn.com/li.lms-analytics/insight.min.js 0 ()
(anonymous) @ (index):7839
(anonymous) @ (index):7839
common.min.js:1 GET https://snap.licdn.com/li.lms-analytics/insight.min.js 0 ()
(anonymous) @ common.min.js:1
(anonymous) @ common.min.js:1
common.min.js:1 GET https://connect.facebook.net/en_US/fbevents.js 0 ()
(anonymous) @ common.min.js:1
(anonymous) @ common.min.js:1
docs.min.js:1 GET https://insitez.blob.core.windows.net/site/3b822357-3fd0-4057-9be7-5cbd1f42ad36.js 0 ()
(anonymous) @ docs.min.js:1
(anonymous) @ docs.min.js:1
log.olark.com/jslog/log.png?version=-bucket4&location=https%3A%2F%2Fwww.tinymce.com%2Fdocs%2Fdemo%2Ffile-picker%2F&message=already%20booted%20once%2C%20but%20lost%20olfsk&tabname=oktab2675001144607807&conversation_id=h9BUu5BMzTBCSbHL2E2BZ0T67TEZkTdr&visitor_id=gd5tXcHLPKu1DChQ2E2BZ0T07TE63orW&site_id=2151-351-10-2762&bucket=bucket4&level=warn&timestamp=1525703687803&properties=%7B%7D&recent_logs=%5B%5D:1 GET https://log.olark.com/jslog/log.png?version=-bucket4&location=https%3A%2F%2Fwww.tinymce.com%2Fdocs%2Fdemo%2Ffile-picker%2F&message=already%20booted%20once%2C%20but%20lost%20olfsk&tabname=oktab2675001144607807&conversation_id=h9BUu5BMzTBCSbHL2E2BZ0T67TEZkTdr&visitor_id=gd5tXcHLPKu1DChQ2E2BZ0T07TE63orW&site_id=2151-351-10-2762&bucket=bucket4&level=warn&timestamp=1525703687803&properties=%7B%7D&recent_logs=%5B%5D 0 ()
Image (async)
e._send @ application2.js?v=1525702116294:15
e.log @ application2.js?v=1525702116294:15
e.warn @ application2.js?v=1525702116294:15
c @ application2.js?v=1525702116294:16
i @ application2.js?v=1525702116294:16
r @ application2.js?v=1525702116294:16
(anonymous) @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:16
m @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
a.whenDocumentReady @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
o @ application2.js?v=1525702116294:16
i @ application2.js?v=1525702116294:16
setTimeout (async)
d @ application2.js?v=1525702116294:16
i @ application2.js?v=1525702116294:16
u @ application2.js?v=1525702116294:16
c @ application2.js?v=1525702116294:29
E @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
519.../../chatbox/ApiInstance @ application2.js?v=1525702116294:29
i @ application2.js?v=1525702116294:1
e @ application2.js?v=1525702116294:1
(anonymous) @ application2.js?v=1525702116294:1
storage.js?v=1525702116294:2 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:2:26802)
    at Object.<anonymous> (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:3:539)
    at Object.19../Env (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:3:5858)
    at o (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:1:254)
    at https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:1:305
    at Object.21../Logger (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:3:7530)
    at o (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:1:254)
    at https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:1:305
    at Object.27.../../chatbox/framestorewithjson (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:3:25707)
    at o (https://static.olark.com/jsclient-bucket4/storage.js?v=1525702116294:1:254)
e @ storage.js?v=1525702116294:2
(anonymous) @ storage.js?v=1525702116294:3
19../Env @ storage.js?v=1525702116294:3
o @ storage.js?v=1525702116294:1
(anonymous) @ storage.js?v=1525702116294:1
21../Logger @ storage.js?v=1525702116294:3
o @ storage.js?v=1525702116294:1
(anonymous) @ storage.js?v=1525702116294:1
27.../../chatbox/framestorewithjson @ storage.js?v=1525702116294:3
o @ storage.js?v=1525702116294:1
e @ storage.js?v=1525702116294:1
(anonymous) @ storage.js?v=1525702116294:1
7w4jkv:10 GET https://pi.pardot.com/pd.js 0 ()
async_load @ 7w4jkv:10
load (async)
(anonymous) @ 7w4jkv:13
(anonymous) @ 7w4jkv:14
common.min.js:1 GET https://pi.pardot.com/pd.js 0 ()
e @ common.min.js:1
load (async)
(anonymous) @ common.min.js:1
(anonymous) @ common.min.js:1
tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8:347684
    at https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8:350376
(anonymous) @ tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8
(anonymous) @ tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8
pen.js:2 Uncaught ReferenceError: tinymce is not defined
    at pen.js:2
(anonymous) @ pen.js:2
log.olark.com/jslog/log.png?version=-bucket4&location=https%3A%2F%2Fwww.tinymce.com%2Fdocs%2Fdemo%2Ffile-picker%2F&message=slow%20data%20connection%20(%3E8s)&tabname=oktab2675001144607807&conversation_id=h9BUu5BMzTBCSbHL2E2BZ0T67TEZkTdr&visitor_id=gd5tXcHLPKu1DChQ2E2BZ0T07TE63orW&site_id=2151-351-10-2762&bucket=bucket4&level=warn&timestamp=1525703695807&properties=%7B%7D&recent_logs=%5B%5D:1 GET https://log.olark.com/jslog/log.png?version=-bucket4&location=https%3A%2F%2Fwww.tinymce.com%2Fdocs%2Fdemo%2Ffile-picker%2F&message=slow%20data%20connection%20(%3E8s)&tabname=oktab2675001144607807&conversation_id=h9BUu5BMzTBCSbHL2E2BZ0T67TEZkTdr&visitor_id=gd5tXcHLPKu1DChQ2E2BZ0T07TE63orW&site_id=2151-351-10-2762&bucket=bucket4&level=warn&timestamp=1525703695807&properties=%7B%7D&recent_logs=%5B%5D 0 ()
Image (async)
e._send @ application2.js?v=1525702116294:15
e.log @ application2.js?v=1525702116294:15
e.warn @ application2.js?v=1525702116294:15
(anonymous) @ application2.js?v=1525702116294:16
setTimeout (async)
i @ application2.js?v=1525702116294:16
r @ application2.js?v=1525702116294:16
(anonymous) @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:16
m @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
a.whenDocumentReady @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
o @ application2.js?v=1525702116294:16
i @ application2.js?v=1525702116294:16
setTimeout (async)
d @ application2.js?v=1525702116294:16
i @ application2.js?v=1525702116294:16
u @ application2.js?v=1525702116294:16
c @ application2.js?v=1525702116294:29
E @ application2.js?v=1525702116294:29
(anonymous) @ application2.js?v=1525702116294:29
519.../../chatbox/ApiInstance @ application2.js?v=1525702116294:29
i @ application2.js?v=1525702116294:1
e @ application2.js?v=1525702116294:1
(anonymous) @ application2.js?v=1525702116294:1

**Comment by fyrkant** [comment] 2018-05-08 01:19
Is it really broken, not just throwing errors caused by the adblocker blocking some scripts? It throws error for me but seems to work fine, so I'm closing this.

**Closed by fyrkant** 2018-05-08 01:19 UTC
