### ISSUE TITLE
ASP.NET CORE MVC

### ISSUE THREAD

**Issue by mankgwanyanetlaka** [tinymce/tinymce-docs#1404] opened 2020-02-15 13:56 UTC
Hi,  I realized you don't support ASP.NET Core

**Comment by tylerkelly13** [comment] 2020-02-18 00:57
Hi @mankgwanyanetlaka,
The question/issue isn't clear. Based on the subject, I'm marking this as a duplicate of ticket #530 .
If you have more information, please reopen this ticket or comment on #530 .

**Closed by tylerkelly13** 2020-02-18 00:57 UTC
Labels: duplicate
