### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#108] opened 2015-11-11 22:47 UTC
### [Codesample Plugin](plugins/codesample.md) issue:
At the end of the article it states the following:
'Of course, you could also use other client side syntax highlighters if you prefer.'
If we are going to state that it is possible, we should probably provide a hint as to how to do that.

**Comment by r12s** [comment] 2015-11-12 16:08
Duplicate of issue #30 

I have removed this text but it may be reintroduced when #30 is resolved, e.g. if there are key/value options that make it easy for devs to implement a different highlighter.

**Closed by r12s** 2015-11-12 16:08 UTC
