### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by JoshMoreno** [tinymce/tinymce-docs#449] opened 2016-12-07 06:03 UTC
> *affected page: https://www.tinymce.com/docs/plugins/codesample/*

So I'm not entirely sure where to post this, but I'll try here since the docs aren't too clear. 

This Code Sample plugin only works for inserting code, but it doesn't appear to let you edit the code after it's inserted. The button tooltip and dialog window both say "Insert/Edit code sample", but I can't find anything in the docs hinting at how to achieve this.

The [full featured example](https://www.tinymce.com/docs/demo/full-featured/) has Code Sample enabled, but unfortunately it doesn't let you edit code after it's inserted either.

Any idea on how to get it working?

**Comment by JoshMoreno** [comment] 2016-12-07 07:27
I dug through the source code and got it working.

Lines 1307 - 1313

```
editor.addCommand('codesample', function() {
    if (editor.selection.isCollapsed()) {
        Dialog.open(editor);
    } else {
        editor.formatter.toggle('code');
    }
});
```

If you just change the else statement to 

    Dialog.open(editor);

then it works as expected.

Or you could just get rid of that whole if else block and just leave the `Dialog.open(editor)`

Whatever floats your boat. 

Is this a bug? Or am I messing with something else and not realizing it? Or both?

**Comment by fyrkant** [comment] 2016-12-20 12:14
Duplicate of tinymce/tinymce#3383, has been fixed in upcoming release.

**Closed by fyrkant** 2016-12-20 12:14 UTC
