### ISSUE TITLE
Problem with page advanced/creating-custom-dialogs.md

### ISSUE THREAD

**Issue by jvega190** [tinymce/tinymce-docs#959] opened 2019-03-01 17:06 UTC
> *affected page: https://www.tinymce.com/docs/advanced/creating-custom-dialogs/*

I used this configuration for opening a dialog with custom html

`var _dialog = editor.windowManager.open({
	title: 'My html dialog',
	url: 'dialog-content.html',
	width: 700,
        height: 600
}, {
	arg1: 42,
	arg2: 'Hello world'
});`

but it seems to be outdated, since it gives me this error:

`Failed path: (dialog)
Could not find valid *strict* value for "body" in {
  "title": "My html dialog",
  "url": "dialog-content.html",
  "width": 700,
  "height": 600
},Failed path: (dialog)
Could not find valid *strict* value for "buttons" in {
  "title": "My html dialog",
  "url": "dialog-content.html",
  "width": 700,
  "height": 600
}....`

The whole creating custom plugin it's being hard for me on tinymce5, since I haven't found proper documentation for that, seems like it's all outdated and non outdated docs are incomplete (missing params/config/etc documentation).
I'd be thankful if this section gets an update so we can create our own plugins. Thanks!

**Comment by reynave** [comment] 2019-03-18 09:45
same here.. 
I thought it's big...

**Comment by lnewson** [comment] 2019-04-15 06:18
Thanks for the report! This is largely a duplicate of https://github.com/tinymce/tinymce-docs/issues/999, as it seems some pages didn't get unpublished sorry! That should be resolved now and we've also brought back our page on creating plugins in TinyMCE 5.0: https://www.tiny.cloud/docs/advanced/creating-a-plugin/

**Closed by lnewson** 2019-04-15 06:18 UTC
