### ISSUE TITLE
Context Menu not working even in documentation

### ISSUE THREAD

**Issue by japhfortin** [tinymce/tinymce-docs#2089] opened 2021-09-02 09:18 UTC
**Documentation/Product Version**
_TinyMCE 4 Documentation_ OR _TinyMCE 5 Documentation_

**Links to Page(s) affected**
https://www.tiny.cloud/docs/ui-components/contextmenu/#interactiveexample

**Description of Issue**
If I understand correctly, context menu is supposed to be the menu that shows when you right click in the editor, right? But I think it is not working even in the documentation page?
![image](https://user-images.githubusercontent.com/29589649/131817973-d897bbc1-0e1d-4d7d-a097-604238f3acc9.png)

**Suggested Fix**

**Comment by tylerkelly13** [comment] 2021-09-03 03:59
Hi @japhfortin 

I can't reproduce this issue on Chrome or Firefox. Can you please provide more details?

Tyler

**Comment by tylerkelly13** [comment] 2021-09-10 04:13
Closing this issue due to lack of information.
Please create a new issue if this issue should not have been closed.

**Closed by tylerkelly13** 2021-09-10 04:13 UTC
Labels: bug
