### ISSUE TITLE
Activate or block: "save button"

### ISSUE THREAD

**Issue by engineer77721** [tinymce/tinymce-docs#1881] opened 2021-02-22 10:31 UTC
How to pass true or false from the save_onsavecallback function: function () {console.log ('Saved'); } in parameter: save_enablewhendirty: ****?

https://www.tiny.cloud/docs/plugins/opensource/save/

**Comment by tylerkelly13** [comment] 2021-02-23 00:19
Closing as a duplicate of https://github.com/tinymce/tinymce-docs/issues/1880

**Closed by tylerkelly13** 2021-02-23 00:19 UTC
Labels: duplicate
